@Library('jenkins-library@main')_

pipeline {
    agent {
        label 'master'
    }

    environment {        
        GIT_AWS_SRC_DEPLOY  = "${GIT_AWS_IAC_DATAPLATFORM}"
        GIT_AWS_SRC_BRANCH 	= 'main'
        TF_BACKEND_BUCKET_KEY = 'dataplatform/terraform.tfstate'
        ENVIRONMENT         = 'develop'
    }

    stages {
    	stage ('Prepare') {
            steps {
				script {                    
					gitHandlerLibrary.checkout(repository=GIT_AWS_SRC_DEPLOY, branch=GIT_AWS_SRC_BRANCH)                    
                    version = 'latest'
				}
            }
        }

        stage ('AWS Init') {
            steps {
				script{
                    terraformHandlerLibrary.createAwsBackend(_bucketKey=TF_BACKEND_BUCKET_KEY, _environment=ENVIRONMENT)
                    terraformHandlerLibrary.initialize()
                }	
            }
        }

        stage ('AWS Plan') {
            steps {
				script{                    
                    terraformHandlerLibrary.plan()
                }	
            }
        }

        stage ('AWS Checkov') {
            steps {
                sh 'echo "AWS Checkov"'	
            }
        }

        stage ('AWS Infra Cost') {
            steps {
                sh 'echo "AWS Infra Cost"'	
            }
        }

        stage ('AWS Apply') {
            steps {
                sh 'echo "AWS Apply"'
            }
        }
    }
	post {
	    always {
		    cleanWs()
	    }
    }
}
