@Library('jenkins-library@main')_

pipeline {
    agent {
        label 'master'
    }

    environment {        
        GIT_AWS_SRC_DEPLOY  = "${GIT_AWS_IAC_DATAPLATFORM}"
        GIT_AWS_SRC_BRANCH 	= 'main'
        GIT_AWS_BACKEND_NAME = 'backend.ft'
        GIT_AWS_BACKEND_DIR = 'Develop/DataPlatform'
    }

    stages {
    	stage ('Prepare') {
            steps {
				script {
                    //terraformHandlerLibrary.createAwsBackend(backendDir=GIT_AWS_BACKEND_DIR+'/'+GIT_AWS_BACKEND_NAME)
					gitHandlerLibrary.checkout(repository=GIT_AWS_SRC_DEPLOY, branch=GIT_AWS_SRC_BRANCH)                    
                    version = 'latest'
				}
                sh 'ls -l'
            }
        }

        stage ('AWS Init') {
            steps {
				sh 'echo "AWS Init"'	
            }
        }

        stage ('AWS Plan') {
            steps {
				sh 'echo "AWS Plan"'	
            }
        }

        stage ('AWS Checkov') {
            steps {
                sh 'echo "AWS Checkov"'	
            }
        }

        stage ('AWS Infra Cost') {
            steps {
                sh 'echo "AWS Infra Cost"'	
            }
        }

        stage ('AWS Apply') {
            steps {
                sh 'echo "AWS Apply"'
            }
        }
    }
	post {
	    always {
		    cleanWs()
	    }
    }
}
